# Generated by Django 5.2.1 on 2025-06-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listing_price_remove_user_id_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='highest_bid', to='auctions.listing'),
        ),
    ]
